galaxy_info:
  author: Anton Markelov
  description: Sample for Hexlet
  company: Hexlet
  license: BSD
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - 8
  galaxy_tags: []
